status = [
  "buildkite/cardano-wallet", 
  "buildkite/cardano-wallet-checks-compiled-commit", 
  "buildkite/cardano-wallet-checks-compiled-merge",
  "%docs%"
]
timeout_sec = 14400
required_approvals = 1
delete_merged_branches = false
