env:
  LC_ALL: "en_US.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

  # Per-container variables
  SCRATCH_DIR: "/scratch/cardano-wallet"
  XDG_STATE_HOME: "/build/cardano-wallet/.state"
  XDG_CACHE_HOME: "/build/cardano-wallet/.cache"

  # Per-host variables - shared across containers on host
  CACHE_DIR: "/cache/cardano-wallet"

steps:
  - label: 'Restore benchmark - cardano mainnet'
    command: "scripts/buildkite/bench-restore.sh mainnet"
    env:
      HOME: "/cache/cardano-wallet.home"
    timeout_in_minutes: 600
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /restore-mainnet/'

# Temporary disabled due to timing out (#2221)
#  - label: 'Restore benchmark - cardano testnet'
#    command: "scripts/buildkite/bench-restore.sh testnet"
#    env:
#      HOME: "/cache/cardano-wallet.home"
#    timeout_in_minutes: 600
#    agents:
#      system: x86_64-linux
#      queue: benchmark
#    if: 'build.env("step") == null || build.env("step") =~ /restore-testnet/'

  - label: 'Database benchmark'
    command: "scripts/buildkite/bench-db.sh"
    timeout_in_minutes: 210
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /bench-db/'

  - label: 'Latency benchmark'
    command: "scripts/buildkite/bench-latency.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux
      queue: benchmark
    if: 'build.env("step") == null || build.env("step") =~ /bench-latency/'

  - wait

  - label: "Advance benchmarks-pass branch"
    command: "scripts/buildkite/push-branch.sh benchmarks-pass"
    agents:
      system: x86_64-linux
    if: 'build.env("step") == null'
