name: Coding Standards

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    
    - name: 📥 Add packages
      shell: bash
      run: |
        apt install -y libtinfo5 
        apt install -y tree

    - name: 📥 Check out repository
      uses: actions/checkout@v2.3.3
      with:
        submodules: true

    - name: 🔬 Check hlint
      shell: bash
      env:
        PACKAGE: hlint
        REPOSITORY: ndmitchell/hlint
        PLATFORM: x86_64-linux
        RELEASE: v3.3.1
        VERSION: 3.3.1
      run: |
        apt install -y libtinfo5 
        scripts/exe-from-github.sh -h .hlint.yaml lib

    - name: ✍  Check stylish-haskell
      shell: bash
      env:
        PACKAGE: stylish-haskell
        REPOSITORY: haskell/stylish-haskell
        PLATFORM: linux-x86_64
        RELEASE: v0.11.0.0
        VERSION: v0.11.0.0
      run: |
        scripts/exe-from-github.sh -i $(git ls-files '*.hs') 
        if [ -z "$(git status --porcelain)" ]; then
            echo "No style errors detected."
        else
            echo "Style errors detected:"
            git diff
            exit 1
        fi
